import type { SpecType, StockStatus } from "@prisma/client";

export type ProductSeed = {
  title: string;
  brand: string;
  slug: string;
  category: string;
  price: number;
  salePrice?: number;
  isSale?: boolean;
  stockStatus?: StockStatus;
  imageUrl: string;
  specType?: SpecType;
  specifications: { key: string; value: string }[] | string[];
  popularity?: number;
};

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=85`;

export const PRODUCT_CATEGORIES = [
  "Laptops",
  "Smartphones",
  "Audio & Speakers",
  "Mobile Accessories",
  "Tablets",
  "TV & Home Appliances",
  "Computer & Accessories",
  "Apple",
  "Cables",
  "Students Deals",
  "Printers",
  "Storage",
] as const;

export const PRODUCT_SEED: ProductSeed[] = [
  // ─── Laptops ───
  {
    title: "MacBook Air 13\" M3 8GB 256GB",
    brand: "Apple",
    slug: "macbook-air-13-m3-256gb",
    category: "Laptops",
    price: 189999,
    salePrice: 179999,
    isSale: true,
    popularity: 95,
    imageUrl: img("photo-1517336714731-489689fd1ca8"),
    specifications: [
      { key: "Processor", value: "Apple M3 chip" },
      { key: "RAM", value: "8GB unified memory" },
      { key: "Storage", value: "256GB SSD" },
      { key: "Display", value: "13.6\" Liquid Retina" },
      { key: "Warranty", value: "1 year" },
    ],
  },
  {
    title: "HP Pavilion 15 Core i5 16GB 512GB SSD",
    brand: "HP",
    slug: "hp-pavilion-15-i5-512gb",
    category: "Laptops",
    price: 89999,
    popularity: 78,
    imageUrl: img("photo-1496181133206-80ce9b88a853"),
    specifications: [
      { key: "Processor", value: "Intel Core i5 13th Gen" },
      { key: "RAM", value: "16GB DDR4" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "15.6\" FHD IPS" },
    ],
  },
  {
    title: "Lenovo IdeaPad Slim 3 Ryzen 5 8GB 512GB",
    brand: "Lenovo",
    slug: "lenovo-ideapad-slim-3-ryzen5",
    category: "Laptops",
    price: 74999,
    salePrice: 69999,
    isSale: true,
    popularity: 72,
    imageUrl: img("photo-1588872657578-7efd1f1555ed"),
    specifications: [
      { key: "Processor", value: "AMD Ryzen 5" },
      { key: "RAM", value: "8GB DDR4" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Weight", value: "1.63 kg" },
    ],
  },
  {
    title: "Dell Inspiron 14 Plus Core i7 16GB 1TB",
    brand: "Dell",
    slug: "dell-inspiron-14-plus-i7",
    category: "Laptops",
    price: 134999,
    popularity: 65,
    imageUrl: img("photo-1593642632823-8f785ba67e45"),
    specifications: [
      { key: "Processor", value: "Intel Core i7 13th Gen" },
      { key: "RAM", value: "16GB DDR5" },
      { key: "Storage", value: "1TB SSD" },
      { key: "Display", value: "14\" 2.2K" },
    ],
  },
  {
    title: "ASUS VivoBook 15 Intel Core i3 8GB 256GB",
    brand: "ASUS",
    slug: "asus-vivobook-15-i3",
    category: "Laptops",
    price: 54999,
    stockStatus: "LOW_STOCK",
    popularity: 58,
    imageUrl: img("photo-1593642632823-8f785ba67e45"),
    specifications: [
      { key: "Processor", value: "Intel Core i3 12th Gen" },
      { key: "RAM", value: "8GB DDR4" },
      { key: "Storage", value: "256GB SSD" },
      { key: "Display", value: "15.6\" FHD" },
    ],
  },

  // ─── Smartphones ───
  {
    title: "Samsung Galaxy S24 Ultra 256GB",
    brand: "Samsung",
    slug: "samsung-galaxy-s24-ultra-256",
    category: "Smartphones",
    price: 189999,
    salePrice: 174999,
    isSale: true,
    popularity: 98,
    imageUrl: img("photo-1610945265064-0e34e5519bbf"),
    specifications: [
      { key: "Display", value: "6.8\" Dynamic AMOLED 2X" },
      { key: "Storage", value: "256GB" },
      { key: "Camera", value: "200MP main + 50MP periscope" },
      { key: "Battery", value: "5000mAh" },
    ],
  },
  {
    title: "iPhone 15 128GB",
    brand: "Apple",
    slug: "iphone-15-128gb",
    category: "Smartphones",
    price: 149999,
    popularity: 92,
    imageUrl: img("photo-1695048133142-1a20484d2569"),
    specifications: [
      { key: "Display", value: "6.1\" Super Retina XDR" },
      { key: "Storage", value: "128GB" },
      { key: "Chip", value: "A16 Bionic" },
      { key: "Camera", value: "48MP dual system" },
    ],
  },
  {
    title: "Google Pixel 8 Pro 128GB",
    brand: "Google",
    slug: "google-pixel-8-pro-128",
    category: "Smartphones",
    price: 129999,
    salePrice: 119999,
    isSale: true,
    popularity: 70,
    imageUrl: img("photo-1610945265064-0e34e5519bbf"),
    specifications: [
      { key: "Display", value: "6.7\" LTPO OLED" },
      { key: "Storage", value: "128GB" },
      { key: "Chip", value: "Google Tensor G3" },
      { key: "Camera", value: "50MP triple lens" },
    ],
  },
  {
    title: "Xiaomi Redmi Note 13 Pro 256GB",
    brand: "Xiaomi",
    slug: "xiaomi-redmi-note-13-pro",
    category: "Smartphones",
    price: 44999,
    popularity: 85,
    imageUrl: img("photo-1511707171634-5f897ff02aa9"),
    specifications: [
      { key: "Display", value: "6.67\" AMOLED 120Hz" },
      { key: "Storage", value: "256GB" },
      { key: "RAM", value: "8GB" },
      { key: "Battery", value: "5100mAh" },
    ],
  },
  {
    title: "Tecno Camon 30 Premier 512GB",
    brand: "Tecno",
    slug: "tecno-camon-30-premier",
    category: "Smartphones",
    price: 54999,
    popularity: 62,
    imageUrl: img("photo-1556656793-08538906a9f8"),
    specifications: [
      { key: "Display", value: "6.78\" AMOLED" },
      { key: "Storage", value: "512GB" },
      { key: "RAM", value: "12GB" },
      { key: "Camera", value: "50MP OIS main" },
    ],
  },

  // ─── Audio & Speakers ───
  {
    title: "Sony WH-1000XM5 Wireless Headphones",
    brand: "Sony",
    slug: "sony-wh-1000xm5",
    category: "Audio & Speakers",
    price: 49999,
    salePrice: 44999,
    isSale: true,
    popularity: 88,
    imageUrl: img("photo-1618366712010-f4ae9c647dcb"),
    specifications: [
      { key: "Type", value: "Over-ear wireless" },
      { key: "ANC", value: "Industry-leading noise canceling" },
      { key: "Battery", value: "Up to 30 hours" },
      { key: "Connectivity", value: "Bluetooth 5.2" },
    ],
  },
  {
    title: "JBL Flip 6 Portable Bluetooth Speaker",
    brand: "JBL",
    slug: "jbl-flip-6",
    category: "Audio & Speakers",
    price: 18999,
    popularity: 75,
    imageUrl: img("photo-1608043152269-423dbba4e7e1"),
    specifications: [
      { key: "Output", value: "30W RMS" },
      { key: "Waterproof", value: "IP67 rated" },
      { key: "Battery", value: "Up to 12 hours" },
      { key: "Connectivity", value: "Bluetooth 5.1" },
    ],
  },
  {
    title: "Apple AirPods Pro 2nd Gen USB-C",
    brand: "Apple",
    slug: "apple-airpods-pro-2-usbc",
    category: "Audio & Speakers",
    price: 34999,
    popularity: 90,
    imageUrl: img("photo-1608043152269-423dbba4e7e1"),
    specifications: [
      { key: "Type", value: "In-ear true wireless" },
      { key: "ANC", value: "Active Noise Cancellation" },
      { key: "Case", value: "USB-C MagSafe charging" },
      { key: "Chip", value: "H2" },
    ],
  },
  {
    title: "Samsung HW-Q600C Soundbar",
    brand: "Samsung",
    slug: "samsung-hw-q600c-soundbar",
    category: "Audio & Speakers",
    price: 64999,
    salePrice: 57999,
    isSale: true,
    popularity: 55,
    imageUrl: img("photo-1545454675-3531b543be5d"),
    specifications: [
      { key: "Channels", value: "3.1.2ch" },
      { key: "Dolby Atmos", value: "Yes" },
      { key: "Subwoofer", value: "Wireless included" },
      { key: "Connectivity", value: "HDMI eARC, Bluetooth" },
    ],
  },
  {
    title: "Anker Soundcore Life Q30",
    brand: "Anker",
    slug: "anker-soundcore-life-q30",
    category: "Audio & Speakers",
    price: 12999,
    popularity: 68,
    imageUrl: img("photo-1618366712010-f4ae9c647dcb"),
    specifications: [
      { key: "Type", value: "Over-ear wireless" },
      { key: "ANC", value: "Hybrid active noise canceling" },
      { key: "Battery", value: "Up to 40 hours" },
      { key: "Modes", value: "Transport, Outdoor, Indoor" },
    ],
  },

  // ─── Mobile Accessories ───
  {
    title: "Anker 65W GaN USB-C Charger",
    brand: "Anker",
    slug: "anker-65w-gan-charger",
    category: "Mobile Accessories",
    price: 4999,
    popularity: 80,
    imageUrl: img("photo-1558618666-fcd25c85cd64"),
    specifications: [
      { key: "Power", value: "65W max output" },
      { key: "Ports", value: "2× USB-C" },
      { key: "Technology", value: "GaN II" },
      { key: "Compatibility", value: "Phones, tablets, laptops" },
    ],
  },
  {
    title: "Spigen Ultra Hybrid iPhone 15 Case",
    brand: "Spigen",
    slug: "spigen-ultra-hybrid-iphone-15",
    category: "Mobile Accessories",
    price: 3499,
    popularity: 60,
    imageUrl: img("photo-1695048133142-1a20484d2569"),
    specifications: [
      { key: "Compatibility", value: "iPhone 15" },
      { key: "Material", value: "TPU + polycarbonate" },
      { key: "Protection", value: "Military-grade drop tested" },
      { key: "Design", value: "Crystal clear back" },
    ],
  },
  {
    title: "Samsung 25W Super Fast Charger",
    brand: "Samsung",
    slug: "samsung-25w-fast-charger",
    category: "Mobile Accessories",
    price: 2999,
    salePrice: 2499,
    isSale: true,
    popularity: 72,
    imageUrl: img("photo-1558618666-fcd25c85cd64"),
    specifications: [
      { key: "Power", value: "25W PPS" },
      { key: "Port", value: "USB-C" },
      { key: "Cable", value: "USB-C to USB-C included" },
    ],
  },
  {
    title: "PopSockets MagSafe Phone Grip",
    brand: "PopSockets",
    slug: "popsockets-magsafe-grip",
    category: "Mobile Accessories",
    price: 3999,
    popularity: 45,
    imageUrl: img("photo-1556656793-08538906a9f8"),
    specifications: [
      { key: "Mount", value: "MagSafe compatible" },
      { key: "Function", value: "Grip + stand" },
      { key: "Compatibility", value: "iPhone 12 and newer" },
    ],
  },
  {
    title: "Belkin 3-in-1 MagSafe Charging Stand",
    brand: "Belkin",
    slug: "belkin-3in1-magsafe-stand",
    category: "Mobile Accessories",
    price: 18999,
    popularity: 52,
    imageUrl: img("photo-1558618666-fcd25c85cd64"),
    specifications: [
      { key: "Charges", value: "iPhone, AirPods, Apple Watch" },
      { key: "Power", value: "15W MagSafe for iPhone" },
      { key: "Design", value: "Compact desktop stand" },
    ],
  },

  // ─── Tablets ───
  {
    title: "iPad Air 11\" M2 128GB Wi-Fi",
    brand: "Apple",
    slug: "ipad-air-11-m2-128gb",
    category: "Tablets",
    price: 99999,
    salePrice: 94999,
    isSale: true,
    popularity: 82,
    imageUrl: img("photo-1544244015-0df4b3ffc6b0"),
    specifications: [
      { key: "Chip", value: "Apple M2" },
      { key: "Storage", value: "128GB" },
      { key: "Display", value: "11\" Liquid Retina" },
      { key: "Connectivity", value: "Wi-Fi 6E" },
    ],
  },
  {
    title: "Samsung Galaxy Tab S9 128GB",
    brand: "Samsung",
    slug: "samsung-galaxy-tab-s9",
    category: "Tablets",
    price: 89999,
    popularity: 70,
    imageUrl: img("photo-1561154464-82e9adf32764"),
    specifications: [
      { key: "Display", value: "11\" Dynamic AMOLED 2X" },
      { key: "Storage", value: "128GB" },
      { key: "RAM", value: "8GB" },
      { key: "S Pen", value: "Included" },
    ],
  },
  {
    title: "Lenovo Tab P12 8GB 256GB",
    brand: "Lenovo",
    slug: "lenovo-tab-p12",
    category: "Tablets",
    price: 54999,
    popularity: 55,
    imageUrl: img("photo-1561154464-82e9adf32764"),
    specifications: [
      { key: "Display", value: "12.7\" 3K" },
      { key: "Storage", value: "256GB" },
      { key: "RAM", value: "8GB" },
      { key: "Battery", value: "10200mAh" },
    ],
  },
  {
    title: "Xiaomi Pad 6 6GB 128GB",
    brand: "Xiaomi",
    slug: "xiaomi-pad-6",
    category: "Tablets",
    price: 42999,
    salePrice: 39999,
    isSale: true,
    popularity: 64,
    imageUrl: img("photo-1633265486064-086b219458ec"),
    specifications: [
      { key: "Display", value: "11\" 2.8K 144Hz" },
      { key: "Storage", value: "128GB" },
      { key: "RAM", value: "6GB" },
      { key: "Chip", value: "Snapdragon 870" },
    ],
  },
  {
    title: "Amazon Fire HD 10 32GB",
    brand: "Amazon",
    slug: "amazon-fire-hd-10",
    category: "Tablets",
    price: 24999,
    popularity: 40,
    imageUrl: img("photo-1544244015-0df4b3ffc6b0"),
    specifications: [
      { key: "Display", value: "10.1\" 1080p" },
      { key: "Storage", value: "32GB" },
      { key: "Battery", value: "Up to 13 hours" },
      { key: "Use case", value: "Media & reading" },
    ],
  },

  // ─── TV & Home Appliances ───
  {
    title: "Samsung 55\" Crystal UHD 4K Smart TV",
    brand: "Samsung",
    slug: "samsung-55-crystal-uhd",
    category: "TV & Home Appliances",
    price: 89999,
    salePrice: 79999,
    isSale: true,
    popularity: 76,
    imageUrl: img("photo-1593359677879-a4bb92f829d1"),
    specifications: [
      { key: "Screen", value: "55\" 4K UHD" },
      { key: "HDR", value: "HDR10+" },
      { key: "Smart TV", value: "Tizen OS" },
      { key: "Refresh", value: "60Hz" },
    ],
  },
  {
    title: "LG 43\" Full HD Smart TV",
    brand: "LG",
    slug: "lg-43-full-hd-smart-tv",
    category: "TV & Home Appliances",
    price: 49999,
    popularity: 58,
    imageUrl: img("photo-1461151304267-38535e780c79"),
    specifications: [
      { key: "Screen", value: "43\" Full HD" },
      { key: "Smart TV", value: "webOS" },
      { key: "Audio", value: "20W dual speakers" },
    ],
  },
  {
    title: "Hisense 65\" ULED 4K Google TV",
    brand: "Hisense",
    slug: "hisense-65-uled-4k",
    category: "TV & Home Appliances",
    price: 119999,
    popularity: 65,
    imageUrl: img("photo-1593359677879-a4bb92f829d1"),
    specifications: [
      { key: "Screen", value: "65\" 4K ULED" },
      { key: "OS", value: "Google TV" },
      { key: "Dolby", value: "Dolby Vision & Atmos" },
    ],
  },
  {
    title: "Philips 2000 Series Air Fryer XXL",
    brand: "Philips",
    slug: "philips-air-fryer-xxl",
    category: "TV & Home Appliances",
    price: 24999,
    salePrice: 21999,
    isSale: true,
    popularity: 48,
    imageUrl: img("photo-1585515320310-259814833e62"),
    specifications: [
      { key: "Capacity", value: "1.4 kg" },
      { key: "Power", value: "2225W" },
      { key: "Technology", value: "Rapid Air" },
      { key: "Dishwasher safe", value: "Yes" },
    ],
  },
  {
    title: "Samsung 7.5kg Front Load Washing Machine",
    brand: "Samsung",
    slug: "samsung-7-5kg-washing-machine",
    category: "TV & Home Appliances",
    price: 74999,
    popularity: 42,
    imageUrl: img("photo-1585515320310-259814833e62"),
    specifications: [
      { key: "Capacity", value: "7.5 kg" },
      { key: "Type", value: "Front load" },
      { key: "Energy", value: "Eco Bubble technology" },
      { key: "Spin", value: "1400 RPM" },
    ],
  },

  // ─── Computer & Accessories ───
  {
    title: "Logitech MX Master 3S Wireless Mouse",
    brand: "Logitech",
    slug: "logitech-mx-master-3s",
    category: "Computer & Accessories",
    price: 14999,
    popularity: 84,
    imageUrl: img("photo-1527864550417-7fd91fc51a46"),
    specifications: [
      { key: "Connectivity", value: "Bluetooth + USB receiver" },
      { key: "Sensor", value: "8000 DPI" },
      { key: "Battery", value: "Up to 70 days" },
      { key: "Buttons", value: "7 programmable" },
    ],
  },
  {
    title: "Keychron K2 Pro Mechanical Keyboard",
    brand: "Keychron",
    slug: "keychron-k2-pro",
    category: "Computer & Accessories",
    price: 18999,
    salePrice: 16999,
    isSale: true,
    popularity: 71,
    imageUrl: img("photo-1587829741301-dc798b83add3"),
    specifications: [
      { key: "Layout", value: "75% compact" },
      { key: "Switches", value: "Gateron Pro Red" },
      { key: "Connectivity", value: "Bluetooth + wired" },
      { key: "Backlight", value: "RGB" },
    ],
  },
  {
    title: "Dell 27\" FHD IPS Monitor",
    brand: "Dell",
    slug: "dell-27-fhd-monitor",
    category: "Computer & Accessories",
    price: 32999,
    popularity: 66,
    imageUrl: img("photo-1527443224154-c4a3942d3acf"),
    specifications: [
      { key: "Size", value: "27 inches" },
      { key: "Resolution", value: "1920 × 1080" },
      { key: "Panel", value: "IPS" },
      { key: "Ports", value: "HDMI, DisplayPort, VGA" },
    ],
  },
  {
    title: "TP-Link Archer AX55 Wi-Fi 6 Router",
    brand: "TP-Link",
    slug: "tp-link-archer-ax55",
    category: "Computer & Accessories",
    price: 12999,
    popularity: 59,
    imageUrl: img("photo-1558494949-ef010cbdcc31"),
    specifications: [
      { key: "Standard", value: "Wi-Fi 6 AX3000" },
      { key: "Coverage", value: "Up to 200 m²" },
      { key: "Ports", value: "4× Gigabit LAN" },
      { key: "Security", value: "HomeShield" },
    ],
  },
  {
    title: "Logitech C920 HD Pro Webcam",
    brand: "Logitech",
    slug: "logitech-c920-webcam",
    category: "Computer & Accessories",
    price: 10999,
    popularity: 53,
    imageUrl: img("photo-1527443224154-c4a3942d3acf"),
    specifications: [
      { key: "Resolution", value: "1080p 30fps" },
      { key: "Focus", value: "Autofocus" },
      { key: "Microphone", value: "Dual stereo" },
      { key: "Mount", value: "Clip + tripod ready" },
    ],
  },

  // ─── Apple ───
  {
    title: "MacBook Pro 14\" M3 Pro 18GB 512GB",
    brand: "Apple",
    slug: "macbook-pro-14-m3-pro",
    category: "Apple",
    price: 289999,
    popularity: 91,
    imageUrl: img("photo-1517336714731-489689fd1ca8"),
    specifications: [
      { key: "Chip", value: "Apple M3 Pro" },
      { key: "RAM", value: "18GB unified memory" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "14.2\" Liquid Retina XDR" },
    ],
  },
  {
    title: "iPhone 15 Pro Max 256GB",
    brand: "Apple",
    slug: "iphone-15-pro-max-256",
    category: "Apple",
    price: 199999,
    salePrice: 189999,
    isSale: true,
    popularity: 96,
    imageUrl: img("photo-1695048133142-1a20484d2569"),
    specifications: [
      { key: "Chip", value: "A17 Pro" },
      { key: "Storage", value: "256GB" },
      { key: "Display", value: "6.7\" Super Retina XDR" },
      { key: "Frame", value: "Titanium" },
    ],
  },
  {
    title: "Apple Watch Series 9 GPS 45mm",
    brand: "Apple",
    slug: "apple-watch-series-9-45mm",
    category: "Apple",
    price: 59999,
    popularity: 74,
    imageUrl: img("photo-1434493789847-2f02dc6ca35d"),
    specifications: [
      { key: "Case", value: "45mm aluminium" },
      { key: "Chip", value: "S9 SiP" },
      { key: "Display", value: "Always-On Retina" },
      { key: "Health", value: "ECG, blood oxygen" },
    ],
  },
  {
    title: "AirPods Max",
    brand: "Apple",
    slug: "apple-airpods-max",
    category: "Apple",
    price: 79999,
    salePrice: 72999,
    isSale: true,
    popularity: 68,
    imageUrl: img("photo-1618366712010-f4ae9c647dcb"),
    specifications: [
      { key: "Type", value: "Over-ear wireless" },
      { key: "ANC", value: "Active Noise Cancellation" },
      { key: "Chip", value: "H1" },
      { key: "Battery", value: "Up to 20 hours" },
    ],
  },
  {
    title: "Magic Keyboard for iPad Pro",
    brand: "Apple",
    slug: "apple-magic-keyboard-ipad-pro",
    category: "Apple",
    price: 44999,
    popularity: 50,
    imageUrl: img("photo-1544244015-0df4b3ffc6b0"),
    specifications: [
      { key: "Compatibility", value: "iPad Pro 11\" & 12.9\"" },
      { key: "Trackpad", value: "Built-in" },
      { key: "Connection", value: "Smart Connector" },
      { key: "Backlight", value: "Yes" },
    ],
  },

  // ─── Cables ───
  {
    title: "Anker USB-C to USB-C 2m 100W Cable",
    brand: "Anker",
    slug: "anker-usbc-100w-2m",
    category: "Cables",
    price: 2499,
    popularity: 77,
    imageUrl: img("photo-1558618666-fcd25c85cd64"),
    specifications: [
      { key: "Length", value: "2 metres" },
      { key: "Power", value: "100W PD" },
      { key: "Data", value: "USB 2.0 480Mbps" },
      { key: "Durability", value: "12,000 bend tested" },
    ],
  },
  {
    title: "Apple USB-C to Lightning Cable 1m",
    brand: "Apple",
    slug: "apple-usbc-lightning-1m",
    category: "Cables",
    price: 3499,
    popularity: 65,
    imageUrl: img("photo-1558618666-fcd25c85cd64"),
    specifications: [
      { key: "Length", value: "1 metre" },
      { key: "Connector", value: "USB-C to Lightning" },
      { key: "Charging", value: "Fast charge compatible" },
    ],
  },
  {
    title: "Baseus HDMI 2.1 Cable 3m",
    brand: "Baseus",
    slug: "baseus-hdmi-2-1-3m",
    category: "Cables",
    price: 3999,
    salePrice: 3299,
    isSale: true,
    popularity: 48,
    imageUrl: img("photo-1558618666-fcd25c85cd64"),
    specifications: [
      { key: "Length", value: "3 metres" },
      { key: "Standard", value: "HDMI 2.1" },
      { key: "Resolution", value: "8K@60Hz / 4K@120Hz" },
    ],
  },
  {
    title: "UGREEN USB-C Hub 7-in-1",
    brand: "UGREEN",
    slug: "ugreen-usbc-hub-7in1",
    category: "Cables",
    price: 6999,
    popularity: 70,
    imageUrl: img("photo-1558618666-fcd25c85cd64"),
    specifications: [
      { key: "Ports", value: "HDMI, 3× USB-A, SD, microSD, USB-C PD" },
      { key: "HDMI", value: "4K@30Hz" },
      { key: "Power delivery", value: "100W pass-through" },
    ],
  },
  {
    title: "Samsung USB-C to USB-C 1.8m",
    brand: "Samsung",
    slug: "samsung-usbc-cable-1-8m",
    category: "Cables",
    price: 1999,
    popularity: 55,
    imageUrl: img("photo-1558618666-fcd25c85cd64"),
    specifications: [
      { key: "Length", value: "1.8 metres" },
      { key: "Power", value: "60W" },
      { key: "Compatibility", value: "Galaxy & USB-C devices" },
    ],
  },

  // ─── Students Deals ───
  {
    title: "HP 14\" Student Laptop Core i3 8GB 256GB",
    brand: "HP",
    slug: "hp-14-student-laptop",
    category: "Students Deals",
    price: 49999,
    salePrice: 44999,
    isSale: true,
    popularity: 88,
    imageUrl: img("photo-1496181133206-80ce9b88a853"),
    specifications: [
      { key: "Processor", value: "Intel Core i3" },
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "256GB SSD" },
      { key: "Ideal for", value: "Assignments & online classes" },
    ],
  },
  {
    title: "Lenovo Chromebook Duet 128GB",
    brand: "Lenovo",
    slug: "lenovo-chromebook-duet-student",
    category: "Students Deals",
    price: 39999,
    salePrice: 35999,
    isSale: true,
    popularity: 72,
    imageUrl: img("photo-1527864550417-7fd91fc51a46"),
    specifications: [
      { key: "OS", value: "Chrome OS" },
      { key: "Storage", value: "128GB" },
      { key: "Display", value: "10.1\" detachable" },
      { key: "Battery", value: "Up to 10 hours" },
    ],
  },
  {
    title: "Xiaomi Redmi Pad SE 4GB 128GB",
    brand: "Xiaomi",
    slug: "xiaomi-redmi-pad-se-student",
    category: "Students Deals",
    price: 29999,
    salePrice: 26999,
    isSale: true,
    popularity: 80,
    imageUrl: img("photo-1633265486064-086b219458ec"),
    specifications: [
      { key: "Display", value: "11\" FHD+" },
      { key: "RAM", value: "4GB" },
      { key: "Storage", value: "128GB" },
      { key: "Ideal for", value: "Notes & e-learning" },
    ],
  },
  {
    title: "Canon PIXMA Student Bundle Pack",
    brand: "Canon",
    slug: "canon-pixma-student-bundle",
    category: "Students Deals",
    price: 18999,
    salePrice: 15999,
    isSale: true,
    popularity: 45,
    imageUrl: img("photo-1586953208448-b95a79798f07"),
    specifications: [
      { key: "Includes", value: "Printer + 2 ink sets" },
      { key: "Functions", value: "Print, scan, copy" },
      { key: "Connectivity", value: "Wi-Fi" },
    ],
  },
  {
    title: "JBL Tune 520BT Student Headphones",
    brand: "JBL",
    slug: "jbl-tune-520bt-student",
    category: "Students Deals",
    price: 6999,
    salePrice: 5499,
    isSale: true,
    popularity: 62,
    imageUrl: img("photo-1618366712010-f4ae9c647dcb"),
    specifications: [
      { key: "Type", value: "On-ear wireless" },
      { key: "Battery", value: "Up to 57 hours" },
      { key: "Ideal for", value: "Study sessions & commutes" },
    ],
  },

  // ─── Printers ───
  {
    title: "HP LaserJet Pro M404dn",
    brand: "HP",
    slug: "hp-laserjet-pro-m404dn",
    category: "Printers",
    price: 54999,
    popularity: 58,
    imageUrl: img("photo-1586953208448-b95a79798f07"),
    specifications: [
      { key: "Type", value: "Monochrome laser" },
      { key: "Speed", value: "38 ppm" },
      { key: "Connectivity", value: "Ethernet, USB" },
      { key: "Duplex", value: "Automatic" },
    ],
  },
  {
    title: "Canon PIXMA G3411 MegaTank",
    brand: "Canon",
    slug: "canon-pixma-g3411",
    category: "Printers",
    price: 32999,
    salePrice: 29999,
    isSale: true,
    popularity: 65,
    imageUrl: img("photo-1586953208448-b95a79798f07"),
    specifications: [
      { key: "Type", value: "Ink tank all-in-one" },
      { key: "Functions", value: "Print, scan, copy" },
      { key: "Yield", value: "Up to 6000 black pages" },
      { key: "Connectivity", value: "Wi-Fi" },
    ],
  },
  {
    title: "Epson EcoTank L3250",
    brand: "Epson",
    slug: "epson-ecotank-l3250",
    category: "Printers",
    price: 38999,
    popularity: 70,
    imageUrl: img("photo-1586953208448-b95a79798f07"),
    specifications: [
      { key: "Type", value: "EcoTank all-in-one" },
      { key: "Functions", value: "Print, scan, copy" },
      { key: "Connectivity", value: "Wi-Fi Direct" },
      { key: "Ink", value: "High-yield refill bottles" },
    ],
  },
  {
    title: "Brother HL-L2400D Laser Printer",
    brand: "Brother",
    slug: "brother-hl-l2400d",
    category: "Printers",
    price: 27999,
    popularity: 48,
    imageUrl: img("photo-1586953208448-b95a79798f07"),
    specifications: [
      { key: "Type", value: "Monochrome laser" },
      { key: "Speed", value: "30 ppm" },
      { key: "Duplex", value: "Automatic" },
      { key: "Connectivity", value: "USB 2.0" },
    ],
  },
  {
    title: "HP DeskJet 2710e All-in-One",
    brand: "HP",
    slug: "hp-deskjet-2710e",
    category: "Printers",
    price: 12999,
    popularity: 52,
    imageUrl: img("photo-1586953208448-b95a79798f07"),
    specifications: [
      { key: "Type", value: "Inkjet all-in-one" },
      { key: "Functions", value: "Print, scan, copy" },
      { key: "Connectivity", value: "Wi-Fi, USB" },
      { key: "HP Smart", value: "Mobile printing" },
    ],
  },

  // ─── Storage ───
  {
    title: "Samsung 1TB T7 Portable SSD",
    brand: "Samsung",
    slug: "samsung-t7-1tb-ssd",
    category: "Storage",
    price: 14999,
    salePrice: 12999,
    isSale: true,
    popularity: 86,
    imageUrl: img("photo-1629654297299-c8506221ca97"),
    specifications: [
      { key: "Capacity", value: "1TB" },
      { key: "Interface", value: "USB 3.2 Gen 2" },
      { key: "Read speed", value: "Up to 1050 MB/s" },
      { key: "Encryption", value: "AES 256-bit" },
    ],
  },
  {
    title: "SanDisk 128GB Ultra microSDXC",
    brand: "SanDisk",
    slug: "sandisk-128gb-ultra-microsd",
    category: "Storage",
    price: 2499,
    popularity: 90,
    imageUrl: img("photo-1629654297299-c8506221ca97"),
    specifications: [
      { key: "Capacity", value: "128GB" },
      { key: "Speed", value: "Up to 140MB/s" },
      { key: "Class", value: "Class 10, UHS-I" },
      { key: "Adapter", value: "SD adapter included" },
    ],
  },
  {
    title: "WD Elements 2TB External HDD",
    brand: "Western Digital",
    slug: "wd-elements-2tb-hdd",
    category: "Storage",
    price: 9999,
    popularity: 74,
    imageUrl: img("photo-1629654297299-c8506221ca97"),
    specifications: [
      { key: "Capacity", value: "2TB" },
      { key: "Interface", value: "USB 3.0" },
      { key: "Form factor", value: "2.5\" portable" },
      { key: "Use case", value: "Backup & media library" },
    ],
  },
  {
    title: "Kingston 32GB USB 3.2 Flash Drive",
    brand: "Kingston",
    slug: "kingston-32gb-usb-flash",
    category: "Storage",
    price: 1499,
    popularity: 68,
    imageUrl: img("photo-1629654297299-c8506221ca97"),
    specifications: [
      { key: "Capacity", value: "32GB" },
      { key: "Interface", value: "USB 3.2 Gen 1" },
      { key: "Cap design", value: "Sliding capless" },
    ],
  },
  {
    title: "Seagate Expansion 4TB Desktop HDD",
    brand: "Seagate",
    slug: "seagate-expansion-4tb",
    category: "Storage",
    price: 14999,
    salePrice: 13499,
    isSale: true,
    popularity: 60,
    imageUrl: img("photo-1629654297299-c8506221ca97"),
    specifications: [
      { key: "Capacity", value: "4TB" },
      { key: "Interface", value: "USB 3.0" },
      { key: "Form factor", value: "3.5\" desktop" },
      { key: "Plug and play", value: "Yes" },
    ],
  },
];
